source 'https://rubygems.org'

gem 'middleman'
gem 'middleman-blog'
gem 'redcarpet'
gem 'geocoder'
gem 'rake'
gem 'fastimage'
gem 'pry'
gem 'font-awesome-middleman'
gem 'middleman-automatic-clowncar'
gem 'middleman-syntax'
gem 'commander'
